'use strict';

class Watchants {

     SCREEN_WIDTH = 144;
     SCREEN_HEIGHT = 168;

     SCR_CONTROL_STATIC_RECT = 0;
     SCR_CONTROL_NUMBER = 1;
     SCR_CONTROL_HORIZONTAL_PROGRESS_BAR = 2;
     SCR_CONTROL_VERTICAL_PROGRESS_BAR = 3;
     SCR_CONTROL_TEXT = 4;
     SCR_CONTROL_STATIC_IMAGE = 5;
     SCR_CONTROL_IMAGE_FROM_SET = 6;
     SCR_CONTROL_CHOOSE = 0xF0;

     MAX_TEXT_EXT_PROPERTY_LENGTH = 253;
     DEFAULT_TEXT_EXT_PROPERTY_LENGTH = 32;

     NUMBER_RANGE_0__9 = 0x10;
     NUMBER_RANGE_0__19 = 0x20;
     NUMBER_RANGE_0__99 = 0x30;
     NUMBER_RANGE_0__199 = 0x40;
     NUMBER_RANGE_0__999 = 0x50;
     NUMBER_RANGE_0__1999 = 0x60;
     NUMBER_RANGE_0__9999 = 0x70;
     NUMBER_RANGE_0__19999 = 0x80;
     NUMBER_RANGE_0__99999 = 0x90;
     NUMBER_RANGE_0__9_9 = 0x11;
     NUMBER_RANGE_0__19_9 = 0x21;
     NUMBER_RANGE_0__99_9 = 0x31;
     NUMBER_RANGE_0__199_9 = 0x41;
     NUMBER_RANGE_0__999_9 = 0x51;
     NUMBER_RANGE_0__1999_9 = 0x61;
     NUMBER_RANGE_0__9999_9 = 0x71;
     NUMBER_RANGE_0__19999_9 = 0x81;
     NUMBER_RANGE_0__99999_9 = 0x91;
     NUMBER_RANGE_0__9_99 = 0x12;
     NUMBER_RANGE_0__19_99 = 0x22;
     NUMBER_RANGE_0__99_99 = 0x32;
     NUMBER_RANGE_0__199_99 = 0x42;
     NUMBER_RANGE_0__999_99 = 0x52;
     NUMBER_RANGE_0__1999_99 = 0x62;
     NUMBER_RANGE_0__9999_99 = 0x72;
     NUMBER_RANGE_0__19999_99 = 0x82;
     NUMBER_RANGE_0__99999_99 = 0x92;

     FONT_NAME_SMALL_REGULAR = 1;
     FONT_NAME_SMALL_BOLD = 2;
     FONT_NAME_NORMAL_REGULAR = 3;
     FONT_NAME_NORMAL_BOLD = 4;
     FONT_NAME_BIG_REGULAR = 5;
     FONT_NAME_BIG_BOLD = 6;
     FONT_NAME_OPTION_NORMAL = 0x10;
     FONT_NAME_OPTION_BIG = 0x11;

     HORIZONTAL_ALIGN_LEFT = 0x0;
     HORIZONTAL_ALIGN_CENTER = 0x40;
     HORIZONTAL_ALIGN_RIGHT = 0x80;

     VERTICAL_ALIGN_TOP = 0x0;
     VERTICAL_ALIGN_CENTER = 0x10;
     VERTICAL_ALIGN_BOTTOM = 0x20;

     TEXT_FLAGS_MULTILINE = 0x8;
     TEXT_FLAGS_SPLIT_WORD = 0x4;

     WATCH_SET_SECTION_SCREENS = 1;
     WATCH_SET_SECTION_EXTERNAL_PROPERTIES = 2;
     WATCH_SET_SECTION_RESOURCES = 3;

     WATCH_SET_SCREEN_SECTION_CONTROLS = 1;
     WATCH_SET_SCREEN_SECTION_ACTIONS = 2;
     WATCH_SET_SCREEN_SECTION_MEMORY = 3;
     WATCH_SET_SCREEN_SECTION_BASE_ACTIONS = 4;
     WATCH_SET_SCREEN_SECTION_MODEL = 5;
     WATCH_SET_SCREEN_SECTION_SETTINGS = 6;

     WATCH_SET_SETTING_INVERTIBLE = 1;

     WATCH_SET_END_OF_DATA = 0xFF;

     DATA_SOURCE_INTERNAL = 0;
     DATA_SOURCE_EXTERNAL = 1;
     DATA_SOURCE_SENSOR = 2;
     DATA_SOURCE_STATIC = 3;
     DATA_SOURCE_WATCHSET_MODEL = 4;

     RESOURCE_SOURCE_ATTACHED = 1;

     INTERNAL_DATA_SOURCE_BATTERY_LEVEL = 0;
     INTERNAL_DATA_SOURCE_TIME_IN_SECONDS = 1;
     INTERNAL_DATA_SOURCE_TIME_HOUR_24 = 2;
     INTERNAL_DATA_SOURCE_TIME_HOUR_12 = 3;
     INTERNAL_DATA_SOURCE_TIME_HOUR_12_DESIGNATOR = 4;
     INTERNAL_DATA_SOURCE_TIME_MINUTES = 5;
     INTERNAL_DATA_SOURCE_TIME_SECONDS = 6;
     INTERNAL_DATA_SOURCE_DATE_DAY_OF_WEEK = 7;
     INTERNAL_DATA_SOURCE_DATE_DAY_OF_MONTH = 8;
     INTERNAL_DATA_SOURCE_DATE_DAY_OF_YEAR = 9;
     INTERNAL_DATA_SOURCE_DATE_MONTH = 10;
     INTERNAL_DATA_SOURCE_DATE_YEAR = 11;
     INTERNAL_DATA_SOURCE_STOPWATCH_TOTAL_TIME = 12;
     INTERNAL_DATA_SOURCE_STOPWATCH_CURRENT_LAP_NUMBER = 13;
     INTERNAL_DATA_SOURCE_STOPWATCH_CURRENT_LAP_TIME = 14;
     INTERNAL_DATA_SOURCE_STOPWATCH_CURRENT_LAP_SPLIT = 15;
     INTERNAL_DATA_SOURCE_STOPWATCH_LAST_LAP_TIME = 16;
     INTERNAL_DATA_SOURCE_STOPWATCH_RECALL_LAP_TIME = 17;
     INTERNAL_DATA_SOURCE_STOPWATCH_RECALL_LAP_SPLIT = 18;
     INTERNAL_DATA_SOURCE_FIRMWARE_VERSION = 19;
     INTERNAL_DATA_SOURCE_MAC_ADDRESS = 20;

     CONVERTER_MS_TO_HOURS = 1;
     CONVERTER_MS_TO_MINUTES_REMAINDER = 2;
     CONVERTER_MS_TO_SECONDS_REMAINDER = 3;
     CONVERTER_MS_TO_CS_REMAINDER = 4;
     CONVERTER_MS_REMAINDER = 5;
     CONVERTER_TIME_TO_HOUR_24 = 6;
     CONVERTER_TIME_TO_ROUNDED_HOUR_24 = 7;
     CONVERTER_TIME_TO_MINUTES = 8;
     CONVERTER_TIME_TO_SECONDS = 9;
     CONVERTER_TIME_TO_FIVE_MINUTES_ROUNDED_TIME = 10;
     CONVERTER_HOUR_24_TO_HOUR_12 = 11;
     CONVERTER_HOUR_24_TO_HOUR_12_PERIOD = 12;
     CONVERTER_MINUTES_TO_PAST_TO_DESIGNATOR = 13;
     CONVERTER_MINUTES_TO_PAST_TO_MINUTES = 14;
     CONVERTER_ONES = 15;
     CONVERTER_TENS = 16;
     CONVERTER_HUNDREDS = 17;

     SENSOR_DATA_SOURCE_HR = 0;
    // INTERNAL_DATA_SOURCE_SENSOR_CYCLING_SPEED = 0x11;
    // INTERNAL_DATA_SOURCE_SENSOR_CYCLING_CADENCE = 0x12;

     WATCHSET_FUNCTION_BACKLIGHT_TOGGLE = 1;
     WATCHSET_FUNCTION_TOGGLE_COLORS = 2;
     WATCHSET_FUNCTION_TEMPORARY_BACKLIGHT = 3;
     WATCHSET_FUNCTION_SET_TEMPORARY_BACKLIGHT_TIMEOUT = 4;
     WATCHSET_FUNCTION_SET_TIME = 5;

     WATCHSET_FUNCTION_FORMAT_DATA = 0xE;
     WATCHSET_FUNCTION_RESTART = 0xF;

     WATCHSET_FUNCTION_STOPWATCH_START = 0x10;
     WATCHSET_FUNCTION_STOPWATCH_RESET = 0x11;
     WATCHSET_FUNCTION_STOPWATCH_STOP = 0x12;
     WATCHSET_FUNCTION_STOPWATCH_START_STOP = 0x13;
     WATCHSET_FUNCTION_STOPWATCH_NEXT_LAP = 0x14;

     WATCHSET_FUNCTION_MODEL_SET = 0xA0;
     WATCHSET_FUNCTION_MODEL_ADD = 0xA1;
     WATCHSET_FUNCTION_MODEL_SUBTRACT = 0xA2;
     WATCHSET_FUNCTION_MODEL_INCREMENT = 0xA3;
     WATCHSET_FUNCTION_MODEL_DECREMENT = 0xA4;

     WATCHSET_FUNCTION_CHANGE_SCREEN = 0xE0;
     WATCHSET_FUNCTION_SHOW_SETTINGS = 0xE1;
     WATCHSET_FUNCTION_SHOW_STATUS = 0xE2;
     WATCHSET_FUNCTION_SHOW_NOTIFICATIONS = 0xE3;
     WATCHSET_FUNCTION_SHOW_WATCH_FACES = 0xE4;
     WATCHSET_FUNCTION_SHOW_APPLICATIONS = 0xE5;
     WATCHSET_FUNCTION_SHOW_UTILS = 0xE6;
     WATCHSET_FUNCTION_SHOW_NEXT_WATCH_FACE = 0xE7;
     WATCHSET_FUNCTION_SHOW_APPLICATION = 0xE8;
     WATCHSET_FUNCTION_SHOW_UTILITY = 0xE9;

     WATCHSET_FUNCTION_CLOSE = 0xEE;
     WATCHSET_FUNCTION_EXTENSION = 0xEF;

     WATCHSET_FUNCTION_CHOOSE = 0xF0;

     EVENT_BUTTON_UP_SHORT = 0;
     EVENT_BUTTON_SELECT_SHORT = 1;
     EVENT_BUTTON_DOWN_SHORT = 2;
     EVENT_BUTTON_BACK_SHORT = 3;
     EVENT_BUTTON_UP_LONG = 4;
     EVENT_BUTTON_SELECT_LONG = 5;
     EVENT_BUTTON_DOWN_LONG = 6;
     EVENT_BUTTON_BACK_LONG = 7;
     EVENT_WRIST_SHAKE = 8;

     OSSW_RX_COMMAND_SET_WATCH_SET_ID = 0x10;
     OSSW_RX_COMMAND_INVOKE_EXTERNAL_FUNCTION = 0x11;
    ;
     OSSW_RX_COMMAND_INVOKE_NOTIFICATION_FUNCTION = 0x12;
     OSSW_RX_COMMAND_UPLOAD_DATA_PERMISSION = 0x20;
     OSSW_RX_COMMAND_COMMAND_ACK = 0x40;
     OSSW_RX_COMMAND_COMMAND_ERROR = 0x41;
     OSSW_RX_COMMAND_UPLOAD_NOTIFICATION_PERMISSION = 0x23;


     FONT_SMALL_REGULAR = 1;
     FONT_SMALL_BOLD = 2;
     FONT_NORMAL_REGULAR = 3;
     FONT_NORMAL_BOLD = 4;
     FONT_BIG_REGULAR = 5;
     FONT_OPTION_NORMAL = 0x10;
     FONT_OPTION_BIG = 0x11;

     NOTIFICATIONS_FUNCTION_DISMISS_ALL = 0x10;
     NOTIFICATIONS_FUNCTION_RESEND = 0x11;
     NOTIFICATIONS_FUNCTION_ALERT_DISMISS = 0x20;
     NOTIFICATIONS_FUNCTION_ALERT_OPTION_1 = 0x21;
     NOTIFICATIONS_FUNCTION_ALERT_OPTION_2 = 0x22;

     NOTIFICATIONS_SHOW_FIRST = 0x30;
     NOTIFICATIONS_NEXT_PART = 0x31;
     NOTIFICATIONS_NEXT = 0x32;
     NOTIFICATIONS_PREV_PART = 0x33;
     NOTIFICATIONS_OPEN = 0x34;
}

export default Watchants;
