'use strict';

class WatchConstants {

    const SCREEN_WIDTH = 144;
    const SCREEN_HEIGHT = 168;

    const SCR_CONTROL_STATIC_RECT = 0;
    const SCR_CONTROL_NUMBER = 1;
    const SCR_CONTROL_HORIZONTAL_PROGRESS_BAR = 2;
    const SCR_CONTROL_VERTICAL_PROGRESS_BAR = 3;
    const SCR_CONTROL_TEXT = 4;
    const SCR_CONTROL_STATIC_IMAGE = 5;
    const SCR_CONTROL_IMAGE_FROM_SET = 6;
    const SCR_CONTROL_CHOOSE = 0xF0;

    const MAX_TEXT_EXT_PROPERTY_LENGTH = 253;
    const DEFAULT_TEXT_EXT_PROPERTY_LENGTH = 32;

    const NUMBER_RANGE_0__9 = 0x10;
    const NUMBER_RANGE_0__19 = 0x20;
    const NUMBER_RANGE_0__99 = 0x30;
    const NUMBER_RANGE_0__199 = 0x40;
    const NUMBER_RANGE_0__999 = 0x50;
    const NUMBER_RANGE_0__1999 = 0x60;
    const NUMBER_RANGE_0__9999 = 0x70;
    const NUMBER_RANGE_0__19999 = 0x80;
    const NUMBER_RANGE_0__99999 = 0x90;
    const NUMBER_RANGE_0__9_9 = 0x11;
    const NUMBER_RANGE_0__19_9 = 0x21;
    const NUMBER_RANGE_0__99_9 = 0x31;
    const NUMBER_RANGE_0__199_9 = 0x41;
    const NUMBER_RANGE_0__999_9 = 0x51;
    const NUMBER_RANGE_0__1999_9 = 0x61;
    const NUMBER_RANGE_0__9999_9 = 0x71;
    const NUMBER_RANGE_0__19999_9 = 0x81;
    const NUMBER_RANGE_0__99999_9 = 0x91;
    const NUMBER_RANGE_0__9_99 = 0x12;
    const NUMBER_RANGE_0__19_99 = 0x22;
    const NUMBER_RANGE_0__99_99 = 0x32;
    const NUMBER_RANGE_0__199_99 = 0x42;
    const NUMBER_RANGE_0__999_99 = 0x52;
    const NUMBER_RANGE_0__1999_99 = 0x62;
    const NUMBER_RANGE_0__9999_99 = 0x72;
    const NUMBER_RANGE_0__19999_99 = 0x82;
    const NUMBER_RANGE_0__99999_99 = 0x92;

    const FONT_NAME_SMALL_REGULAR = 1;
    const FONT_NAME_SMALL_BOLD = 2;
    const FONT_NAME_NORMAL_REGULAR = 3;
    const FONT_NAME_NORMAL_BOLD = 4;
    const FONT_NAME_BIG_REGULAR = 5;
    const FONT_NAME_BIG_BOLD = 6;
    const FONT_NAME_OPTION_NORMAL = 0x10;
    const FONT_NAME_OPTION_BIG = 0x11;

    const HORIZONTAL_ALIGN_LEFT = 0x0;
    const HORIZONTAL_ALIGN_CENTER = 0x40;
    const HORIZONTAL_ALIGN_RIGHT = 0x80;

    const VERTICAL_ALIGN_TOP = 0x0;
    const VERTICAL_ALIGN_CENTER = 0x10;
    const VERTICAL_ALIGN_BOTTOM = 0x20;

    const TEXT_FLAGS_MULTILINE = 0x8;
    const TEXT_FLAGS_SPLIT_WORD = 0x4;

    const WATCH_SET_SECTION_SCREENS = 1;
    const WATCH_SET_SECTION_EXTERNAL_PROPERTIES = 2;
    const WATCH_SET_SECTION_RESOURCES = 3;

    const WATCH_SET_SCREEN_SECTION_CONTROLS = 1;
    const WATCH_SET_SCREEN_SECTION_ACTIONS = 2;
    const WATCH_SET_SCREEN_SECTION_MEMORY = 3;
    const WATCH_SET_SCREEN_SECTION_BASE_ACTIONS = 4;
    const WATCH_SET_SCREEN_SECTION_MODEL = 5;
    const WATCH_SET_SCREEN_SECTION_SETTINGS = 6;

    const WATCH_SET_SETTING_INVERTIBLE = 1;

    const WATCH_SET_END_OF_DATA = 0xFF;

    const DATA_SOURCE_INTERNAL = 0;
    const DATA_SOURCE_EXTERNAL = 1;
    const DATA_SOURCE_SENSOR = 2;
    const DATA_SOURCE_STATIC = 3;
    const DATA_SOURCE_WATCHSET_MODEL = 4;

    const RESOURCE_SOURCE_ATTACHED = 1;

    const INTERNAL_DATA_SOURCE_BATTERY_LEVEL = 0;
    const INTERNAL_DATA_SOURCE_TIME_IN_SECONDS = 1;
    const INTERNAL_DATA_SOURCE_TIME_HOUR_24 = 2;
    const INTERNAL_DATA_SOURCE_TIME_HOUR_12 = 3;
    const INTERNAL_DATA_SOURCE_TIME_HOUR_12_DESIGNATOR = 4;
    const INTERNAL_DATA_SOURCE_TIME_MINUTES = 5;
    const INTERNAL_DATA_SOURCE_TIME_SECONDS = 6;
    const INTERNAL_DATA_SOURCE_DATE_DAY_OF_WEEK = 7;
    const INTERNAL_DATA_SOURCE_DATE_DAY_OF_MONTH = 8;
    const INTERNAL_DATA_SOURCE_DATE_DAY_OF_YEAR = 9;
    const INTERNAL_DATA_SOURCE_DATE_MONTH = 10;
    const INTERNAL_DATA_SOURCE_DATE_YEAR = 11;
    const INTERNAL_DATA_SOURCE_STOPWATCH_TOTAL_TIME = 12;
    const INTERNAL_DATA_SOURCE_STOPWATCH_CURRENT_LAP_NUMBER = 13;
    const INTERNAL_DATA_SOURCE_STOPWATCH_CURRENT_LAP_TIME = 14;
    const INTERNAL_DATA_SOURCE_STOPWATCH_CURRENT_LAP_SPLIT = 15;
    const INTERNAL_DATA_SOURCE_STOPWATCH_LAST_LAP_TIME = 16;
    const INTERNAL_DATA_SOURCE_STOPWATCH_RECALL_LAP_TIME = 17;
    const INTERNAL_DATA_SOURCE_STOPWATCH_RECALL_LAP_SPLIT = 18;
    const INTERNAL_DATA_SOURCE_FIRMWARE_VERSION = 19;
    const INTERNAL_DATA_SOURCE_MAC_ADDRESS = 20;

    const CONVERTER_MS_TO_HOURS = 1;
    const CONVERTER_MS_TO_MINUTES_REMAINDER = 2;
    const CONVERTER_MS_TO_SECONDS_REMAINDER = 3;
    const CONVERTER_MS_TO_CS_REMAINDER = 4;
    const CONVERTER_MS_REMAINDER = 5;
    const CONVERTER_TIME_TO_HOUR_24 = 6;
    const CONVERTER_TIME_TO_ROUNDED_HOUR_24 = 7;
    const CONVERTER_TIME_TO_MINUTES = 8;
    const CONVERTER_TIME_TO_SECONDS = 9;
    const CONVERTER_TIME_TO_FIVE_MINUTES_ROUNDED_TIME = 10;
    const CONVERTER_HOUR_24_TO_HOUR_12 = 11;
    const CONVERTER_HOUR_24_TO_HOUR_12_PERIOD = 12;
    const CONVERTER_MINUTES_TO_PAST_TO_DESIGNATOR = 13;
    const CONVERTER_MINUTES_TO_PAST_TO_MINUTES = 14;
    const CONVERTER_ONES = 15;
    const CONVERTER_TENS = 16;
    const CONVERTER_HUNDREDS = 17;

    const SENSOR_DATA_SOURCE_HR = 0;
    //const INTERNAL_DATA_SOURCE_SENSOR_CYCLING_SPEED = 0x11;
    //const INTERNAL_DATA_SOURCE_SENSOR_CYCLING_CADENCE = 0x12;

    const WATCHSET_FUNCTION_BACKLIGHT_TOGGLE = 1;
    const WATCHSET_FUNCTION_TOGGLE_COLORS = 2;
    const WATCHSET_FUNCTION_TEMPORARY_BACKLIGHT = 3;
    const WATCHSET_FUNCTION_SET_TEMPORARY_BACKLIGHT_TIMEOUT = 4;
    const WATCHSET_FUNCTION_SET_TIME = 5;

    const WATCHSET_FUNCTION_FORMAT_DATA = 0xE;
    const WATCHSET_FUNCTION_RESTART = 0xF;

    const WATCHSET_FUNCTION_STOPWATCH_START = 0x10;
    const WATCHSET_FUNCTION_STOPWATCH_RESET = 0x11;
    const WATCHSET_FUNCTION_STOPWATCH_STOP = 0x12;
    const WATCHSET_FUNCTION_STOPWATCH_START_STOP = 0x13;
    const WATCHSET_FUNCTION_STOPWATCH_NEXT_LAP = 0x14;

    const WATCHSET_FUNCTION_MODEL_SET = 0xA0;
    const WATCHSET_FUNCTION_MODEL_ADD = 0xA1;
    const WATCHSET_FUNCTION_MODEL_SUBTRACT = 0xA2;
    const WATCHSET_FUNCTION_MODEL_INCREMENT = 0xA3;
    const WATCHSET_FUNCTION_MODEL_DECREMENT = 0xA4;

    const WATCHSET_FUNCTION_CHANGE_SCREEN = 0xE0;
    const WATCHSET_FUNCTION_SHOW_SETTINGS = 0xE1;
    const WATCHSET_FUNCTION_SHOW_STATUS = 0xE2;
    const WATCHSET_FUNCTION_SHOW_NOTIFICATIONS = 0xE3;
    const WATCHSET_FUNCTION_SHOW_WATCH_FACES = 0xE4;
    const WATCHSET_FUNCTION_SHOW_APPLICATIONS = 0xE5;
    const WATCHSET_FUNCTION_SHOW_UTILS = 0xE6;
    const WATCHSET_FUNCTION_SHOW_NEXT_WATCH_FACE = 0xE7;
    const WATCHSET_FUNCTION_SHOW_APPLICATION = 0xE8;
    const WATCHSET_FUNCTION_SHOW_UTILITY = 0xE9;

    const WATCHSET_FUNCTION_CLOSE = 0xEE;
    const WATCHSET_FUNCTION_EXTENSION = 0xEF;

    const WATCHSET_FUNCTION_CHOOSE = 0xF0;

    const EVENT_BUTTON_UP_SHORT = 0;
    const EVENT_BUTTON_SELECT_SHORT = 1;
    const EVENT_BUTTON_DOWN_SHORT = 2;
    const EVENT_BUTTON_BACK_SHORT = 3;
    const EVENT_BUTTON_UP_LONG = 4;
    const EVENT_BUTTON_SELECT_LONG = 5;
    const EVENT_BUTTON_DOWN_LONG = 6;
    const EVENT_BUTTON_BACK_LONG = 7;
    const EVENT_WRIST_SHAKE = 8;

    const OSSW_RX_COMMAND_SET_WATCH_SET_ID = 0x10;
    const OSSW_RX_COMMAND_INVOKE_EXTERNAL_FUNCTION = 0x11;
    ;
    const OSSW_RX_COMMAND_INVOKE_NOTIFICATION_FUNCTION = 0x12;
    const OSSW_RX_COMMAND_UPLOAD_DATA_PERMISSION = 0x20;
    const OSSW_RX_COMMAND_COMMAND_ACK = 0x40;
    const OSSW_RX_COMMAND_COMMAND_ERROR = 0x41;
    const OSSW_RX_COMMAND_UPLOAD_NOTIFICATION_PERMISSION = 0x23;


    const FONT_SMALL_REGULAR = 1;
    const FONT_SMALL_BOLD = 2;
    const FONT_NORMAL_REGULAR = 3;
    const FONT_NORMAL_BOLD = 4;
    const FONT_BIG_REGULAR = 5;
    const FONT_OPTION_NORMAL = 0x10;
    const FONT_OPTION_BIG = 0x11;

    const NOTIFICATIONS_FUNCTION_DISMISS_ALL = 0x10;
    const NOTIFICATIONS_FUNCTION_RESEND = 0x11;
    const NOTIFICATIONS_FUNCTION_ALERT_DISMISS = 0x20;
    const NOTIFICATIONS_FUNCTION_ALERT_OPTION_1 = 0x21;
    const NOTIFICATIONS_FUNCTION_ALERT_OPTION_2 = 0x22;

    const NOTIFICATIONS_SHOW_FIRST = 0x30;
    const NOTIFICATIONS_NEXT_PART = 0x31;
    const NOTIFICATIONS_NEXT = 0x32;
    const NOTIFICATIONS_PREV_PART = 0x33;
    const NOTIFICATIONS_OPEN = 0x34;
}

export default WatchConstants;
